NAME    := vlc-server-add-stations.pl
TARGET  := $(NAME) 
BINDIR  := $(DESTDIR)/$(PREFIX)/bin

VERSION := 0.1b

all: $(TARGET)

install:
	mkdir -p $(BINDIR) 
	install -m 755 $(TARGET) ${BINDIR}
	
clean:

