.\" Copyright (C) 2020 Kevin Boone 
.\" Permission is granted to any individual or institution to use, copy, or
.\" redistribute this software so long as all of the original files are
.\" included, that it is not sold for profit, and that this copyright notice
.\" is retained.
.\"
.TH vlc-server 1 "February 2023"
.SH NAME
nc-vlc-client -- a console-based interface for vlc-server media player 

.SH SYNOPSIS
.B vlc-server-client\ [options] 
.PP

.SH DESCRIPTION

\fInc-vlc-client\fR is an ncurses-based, console client for the  
\fIvlc-server\fR media player, which is itself an HTTP interface to the VLC
player. The client allows the audio library to be browsed and played
by album. Other features may be added later. 

.SH "OPTIONS"

.TP
.BI -h,\-\-host={hostname]
.LP
Specify the hostname or IP number of the \fIvlc-server\fR host.
Default: localhost.

.TP
.BI -p,\-\-port={number]
.LP
Specify the IP port number of the \fIvlc-server\fR instance.
Default: 30000.

.SH "DEFAULT KEY BINDINGS"

An alphabetic key moves the current selection in the list to the first
item that starts with that key.

Select a menu or list item: right

Go back to previous meny: left

Next line: down

Previous line: up

Next page: page down

Previous page: page up

Play/pause: space

Next track: ctrl-N

Previous track: ctrl-P

Stop: ctrl-X

Volume up: +

Volume down: -


.\" end of file
